format:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 允许CI推送修改

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: 清除旧版本缓存
      run: |
        pip cache purge
        rm -rf ~/.cache/black

    - name: 安装锁定版本的依赖
      run: pip install -r requirements.txt

    - name: 检查代码格式
      id: format-check
      run: black app/ tests/ --check || echo "format_failed=true" >> $GITHUB_OUTPUT

    - name: 自动格式化代码（若检查失败）
      if: steps.format-check.outputs.format_failed == 'true'
      run: black app/ tests/

    - name: 提交自动格式化结果
      if: steps.format-check.outputs.format_failed == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add app/ tests/
        git commit -m "ci: 自动格式化代码以符合black规范"
        git push origin main